# Generated by Django 5.2.1 on 2025-07-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(
                blank=True,
                help_text="Firebase Cloud Messaging token for push notifications",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="fcm_token_updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When FCM token was last updated"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether user wants to receive push notifications",
            ),
        ),
    ]
