# Generated by Django 5.2.1 on 2025-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_fcm_token_user_fcm_token_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotteryPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(help_text="User identifier", max_length=20),
                ),
                (
                    "lottery_number",
                    models.CharField(help_text="Lottery ticket number", max_length=10),
                ),
                (
                    "lottery_name",
                    models.CharField(help_text="Name of the lottery", max_length=100),
                ),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the lottery ticket",
                        max_digits=10,
                    ),
                ),
                ("purchase_date", models.DateField(help_text="Date of purchase")),
                (
                    "is_winner",
                    models.BooleanField(
                        default=False, help_text="Whether this ticket won any prize"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-purchase_date", "-created_at"],
                "unique_together": {("user_id", "lottery_number", "purchase_date")},
            },
        ),
    ]
