# Generated by Django 5.2.1 on 2025-09-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_lotterypurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotterypurchase",
            name="lottery_unique_id",
            field=models.UUIDField(
                blank=True,
                help_text="Lottery result unique ID for checking wins",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lotterypurchase",
            name="winnings",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prize amount if won",
                max_digits=12,
                null=True,
            ),
        ),
    ]
