# Generated by Django 5.2.1 on 2025-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Unique identifier from mobile app (device/installation ID)",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="User phone number (optional, only for apps with phone auth)",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        choices=[("lotto", "Lotto"), ("lotto lite", "Lotto Lite")],
                        db_index=True,
                        help_text="Application name",
                        max_length=20,
                    ),
                ),
                (
                    "access_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of times this user accessed the app",
                    ),
                ),
                (
                    "first_access",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When user first accessed the app"
                    ),
                ),
                (
                    "last_access",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time user accessed the app"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-last_access"],
                "indexes": [
                    models.Index(
                        fields=["app_name", "-last_access"],
                        name="users_usera_app_nam_cc5742_idx",
                    ),
                    models.Index(
                        fields=["phone_number", "-last_access"],
                        name="users_usera_phone_n_dd4870_idx",
                    ),
                    models.Index(
                        fields=["unique_id", "app_name"],
                        name="users_usera_unique__2ab940_idx",
                    ),
                ],
                "unique_together": {("unique_id", "app_name")},
            },
        ),
    ]
