# Generated by Django 5.2.1 on 2025-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_useractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="unique_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier from mobile app (device/installation ID)",
                max_length=255,
            ),
        ),
    ]
