# Generated by Django 5.2.1 on 2025-10-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_useractivity_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="first_access",
            field=models.DateTimeField(
                help_text="First time user accessed the app today (resets daily)"
            ),
        ),
    ]
