# Generated by Django 5.2.1 on 2026-01-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useractivity_first_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='access_count',
            field=models.IntegerField(default=1, help_text='Number of times this user accessed the app TODAY (resets daily at midnight)'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='first_access',
            field=models.DateTimeField(help_text='First time user accessed the app TODAY (resets daily at midnight)'),
        ),
    ]
