services:
  - type: web
    name: lottery-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn kerala_lottery_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: lottery-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: lottery-db
    databaseName: lottery_db
    user: postgres
    plan: free