# Generated by Django 5.2.1 on 2025-05-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LotteryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("first_prize_amount", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrizeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("amount", models.IntegerField()),
                ("display_amount", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LotteryDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_number", models.IntegerField()),
                ("draw_date", models.DateField()),
                ("result_declared", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=True)),
                (
                    "lottery_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draws",
                        to="lottery.lotterytype",
                    ),
                ),
            ],
            options={
                "ordering": ["-draw_date", "-draw_number"],
                "unique_together": {("lottery_type", "draw_number")},
            },
        ),
        migrations.CreateModel(
            name="WinningTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.CharField(max_length=10)),
                ("number", models.CharField(max_length=10)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winners",
                        to="lottery.lotterydraw",
                    ),
                ),
                (
                    "prize_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winning_tickets",
                        to="lottery.prizecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["prize_category"],
            },
        ),
    ]
