# Generated by Django 5.2.1 on 2025-05-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prizecategory",
            options={
                "verbose_name": "Prize Category",
                "verbose_name_plural": "Prize Categories",
            },
        ),
        migrations.AddField(
            model_name="prizecategory",
            name="lottery_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prize_categories",
                to="lottery.lotterytype",
            ),
        ),
    ]
