# Generated by Django 5.2.1 on 2025-05-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0003_associate_prizes_with_lottery_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lotterydraw",
            options={
                "ordering": ["-draw_date", "-draw_number"],
                "verbose_name": "Lottery History",
                "verbose_name_plural": "Lottery History",
            },
        ),
        migrations.AlterModelOptions(
            name="lotterytype",
            options={"verbose_name": "Lottery", "verbose_name_plural": "Lotteries"},
        ),
    ]
