# Generated by Django 5.2.1 on 2025-05-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0004_alter_lotterydraw_options_alter_lotterytype_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lotterydraw",
            name="is_new",
        ),
    ]
