# Generated by Django 5.2.1 on 2025-05-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0005_remove_lotterydraw_is_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winningticket",
            name="prize_category",
        ),
        migrations.RemoveField(
            model_name="winningticket",
            name="draw",
        ),
        migrations.AlterModelOptions(
            name="lotterydraw",
            options={
                "ordering": ["-draw_date", "-draw_number"],
                "verbose_name": "Lottery Draw",
                "verbose_name_plural": "Lottery Draws",
            },
        ),
        migrations.CreateModel(
            name="ConsolationPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=5000.0, max_digits=10
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolation_prizes",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EighthPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
                ),
                ("number", models.CharField(max_length=4)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eighth_prizes",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FifthPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=100000.0, max_digits=10
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=100)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fifth_prizes",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FirstPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=10000000.0, max_digits=12
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=100)),
                (
                    "draw",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_prize",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FourthPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=1500000.0, max_digits=12
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=100)),
                (
                    "draw",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fourth_prize",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NinthPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
                ),
                ("number", models.CharField(max_length=4)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ninth_prizes",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecondPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=3000000.0, max_digits=12
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=100)),
                (
                    "draw",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_prize",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeventhPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
                ),
                ("number", models.CharField(max_length=4)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seventh_prizes",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SixthPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=5000.0, max_digits=8),
                ),
                ("number", models.CharField(max_length=4)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sixth_prizes",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenthPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
                ),
                ("number", models.CharField(max_length=4)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenth_prizes",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=2500000.0, max_digits=12
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=100)),
                (
                    "draw",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="third_prize",
                        to="lottery.lotterydraw",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PrizeCategory",
        ),
        migrations.DeleteModel(
            name="WinningTicket",
        ),
    ]
