# Generated by Django 5.2.1 on 2025-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0006_remove_winningticket_prize_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotterydraw",
            name="draw_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
